JENKINS-64478 Compatibility with Jenkins >2.263
jenkinsci/flexible-publish-plugin pull request #19
Opened 2020-12-21 10:51 UTC by timja

See https://www.jenkins.io/doc/developer/views/table-to-div-migration/

and https://www.jenkins.io/blog/2019/10/21/plugin-docs-on-github/ for docs migration

I can separate to different PRs if you wish but all commits are self contained

2020-12-30 03:29 UTC, ikedam commented on src/test/java/org/jenkins_ci/plugins/flexible_publish/ConfigurationTest.java
> -    public void testNoDataBoundConstructor() throws Exception {
Note for me: Create an alternate test: https://issues.jenkins.io/browse/JENKINS-64527

2020-12-30 04:46 UTC, ikedam requested changes
Thanks a lot for the fix and updating environments.

It would be simpler to use `<f:repeatableProperty>` as commented.
Can you see about that?
Or I can take over the work if you don't mind.

2020-12-30 04:46 UTC, ikedam commented on src/test/java/org/jenkins_ci/plugins/flexible_publish/ConfigurationTest.java
> +import com.gargoylesoftware.htmlunit.WebClient;
I recommend `org.jvnet.hudson.test.JenkinsRule.WebClient` instead as it provides Jenkins-specific utility methods.

2020-12-30 04:48 UTC, ikedam commented
Somehow, `ConfigurationTest` takes much time and some tests fails for SocketTimeout in my environment.
I'll prepare Jenkinsfile to test this on CI.

2020-12-30 05:36 UTC, ikedam commented
Close and reopen to trigget CI.

2020-12-30 05:47 UTC, timja commented
Please feel free to take this over, thanks!

2020-12-30 06:42 UTC, ikedam commented
link: https://issues.jenkins.io/browse/JENKINS-64478

2021-01-01 03:17 UTC, ikedam commented
I tried to use 2.235.1 preferring the ".1" LTS version [1], but couldn't as run-condition-1.4 with the fix for table-to-div issue [2] targets 2.235.5.

[1] https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/
[2] https://github.com/jenkinsci/run-condition-plugin/pull/22

2021-01-01 03:52 UTC, ikedam approved these changes

2021-01-01 03:52 UTC, merged

2021-01-01 19:28 UTC, oleg-nenashev commented
Belated +1, thanks you @timja and @ikedam !